# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UPAPP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UPAPP
	pod 'Firebase/Core'
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	

  target 'UPAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UPAPPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
